heka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from publicidad import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^publicidad/', include('publicidad.urls', namespace="publicidad")),
    url(r'^$', views.index, name="index"),    
]

publicidad/urls.py
from django.conf.urls import url
from publicidad.views import index, hotel, bodega, entretenimiento, santuario, restaurante,supermercado, \
publico, surtidor, bar, altagracia, sanvicente, churrasqueria_b, plazaTtefarina, petropar, brothers, santo_tomas, \
bacilica_caacupe
#se importan las funciones de las vistas
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^hotel', hotel, name="hotel"),
    url(r'^bodega/', bodega, name="bodega"),
    url(r'^entretenimiento/', entretenimiento, name="entretenimiento"),
    url(r'^santuario/', santuario, name="santuario"),
    url(r'^restaurante/', restaurante, name="restaurante"),    
    url(r'^supermercado/', supermercado, name="supermercado"),
    url(r'^publico/', publico, name="publico"),
    url(r'^surtidor/', surtidor, name="surtidor"),
    url(r'^bar/', bar, name="bar"),
    url(r'^altagracia/', altagracia, name="altagracia"),
    url(r'^sanvicente/', sanvicente, name="sanvicente"),
    url(r'^churrasqueria_b/', churrasqueria_b, name="churrasqueria_b"),
    url(r'^plazaTtefarina/', plazaTtefarina, name="plazaTtefarina"),
    url(r'^petropar/', petropar, name="petropar"),
    url(r'^brothers/', brothers, name="brothers"),
    url(r'^santo_tomas/', santo_tomas, name="santo_tomas"),
    url(r'^bacilica_caacupe/', bacilica_caacupe, name="bacilica_caacupe"),            
]

publicidad/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Categoria(models.Model):
	categoria = models.CharField(max_length=100)

	def __str__(self):
		return self.categoria	
	'''class Meta:
		ordering = ['id_categoria']'''		

class Negocio(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion = models.CharField(max_length=250)
	telefono = models.IntegerField()
	latitud = models.CharField(max_length=100)
	longitud = models.CharField(max_length=100)
	categoria = models.ForeignKey(Categoria) 

	def __str__(self):
		return self.nombre
			

publicidad/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	return render(request, 'publicidad/index.html')

def hotel(request):
	return render(request, 'publicidad/hoteles.html')

def bodega(request):
	return render(request, 'publicidad/bodegas.html')

def entretenimiento(request):
	return render(request, 'publicidad/entretenimiento.html')

def santuario(request):
	return render(request, 'publicidad/santuarios.html')

def restaurante(request):
	return render(request, 'publicidad/restaurante.html')

def supermercado(request):
	return render(request, 'publicidad/supermercado.html')	

def publico(request):
	return render(request,'publicidad/publicos.html')

def surtidor(request):
	return render(request, 'publicidad/surtidor.html')

def bar(request):
	return render(request, 'publicidad/baresYdiscotecas.html')

def altagracia(request):
	return render(request, 'publicidad/hoteles/altagracia.html')

def sanvicente(request):
	return render(request, 'publicidad/supermercados/sanvicente1.html')	

def churrasqueria_b(request):
	return render(request, 'publicidad/restaurantes/churrasqueria_b.html')

def plazaTtefarina(request):
	return render(request, 'publicidad/sector_publico/plazaTteFarina.html')

def petropar(request):
	return render(request, 'publicidad/surtidor/petropar.html')

def brothers(request):
	return render(request, 'publicidad/baresYdiscotecas/brothers.html')

def santo_tomas(request):
	return render(request, 'publicidad/bodegas/Santo_Tomas.html')

def bacilica_caacupe(request):
	return render(request, 'publicidad/santuarios/bacilica_caacupe.html')			

templates/publicidad/baresYdiscotecas.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block banner %} 
{% endblock banner %}
{% block welcome %}
	<!-- welcome -->
				<div class="welcome"> 
					<h3 class="w3ls-title">Bares y Discotecas</h3> 
					<p class="w3title-text">Encuentra tu lugar en Caacupé </p>
					<div class="welcome-info">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">

							<div class="clearfix"> </div>
 

						</div>  
					</div>  	
				</div> 
	<!-- //welcome -->
    
{% endblock welcome %}
{% block properties %}
<div class="w3agile properties">
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/3.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Brother's </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="{% url 'publicidad:brothers' %}"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div> 
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Quinta Verde </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Pilgrims </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> El encuentro </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Casino Caacupe </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> 8.12 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Horarios</b></p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Disco 1 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Disco 2 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" 	alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Disco 3 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Horarios</b></p>
						</div>
					</div>
					<div class="clearfix"> </div>
					
				</div>
    
{% endblock properties %}

templates/publicidad/bodegas.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block banner %} 
{% endblock banner %}
{% block welcome %}
<!-- welcome -->
				<div class="welcome"> 
					<h3 class="w3ls-title">Bodegas </h3> 
					<p class="w3title-text">Encuentra tu lugar en Caacupé </p>
					<div class="welcome-info">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">

							<div class="clearfix"> </div>
 

						</div>  
					</div>  	
				</div> 
<!-- //welcome -->
{% endblock welcome %}
{% block properties %}
<div class="w3agile properties">
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/3.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Santo Tomas </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="{% url 'publicidad:santo_tomas' %}"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div> 
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span>Lubin</h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Lubin 2 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span>La taberna de Moe </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Piratas </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Tercer Tiempo </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Precios</b></p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Russo </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Kafu </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" 	alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Bodega </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Precios</b></p>
						</div>
					</div>
					<div class="clearfix"> </div>
					
				</div>
{% endblock properties %}

templates/publicidad/hoteles.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block banner %} 
{% endblock banner %}
{% block welcome %}
	<!-- welcome -->
				<div class="welcome"> 
					<h3 class="w3ls-title">Hoteles y Moteles </h3> 
					<p class="w3title-text">Encuentra tu lugar en Caacupé </p>
					<div class="welcome-info">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
							<div class="clearfix"> </div>
						</div>  
					</div>  	
				</div> 
	<!-- //welcome -->
{% endblock welcome %}
{% block properties %}
				<div class="w3agile properties">
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/3.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Hotel Asunción </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div> 
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span>Hotel Alta Gracia</h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="{% url 'publicidad:altagracia' %}"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Hotel Katy María </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span>Hotel Copadísimo </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Hotel Uruguayo </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Motel 59 </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Precios</b></p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Motel Piscis </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Motel Carpediem </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Precios</b> </p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" 	alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Hotel Mirador </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Precios</b></p>
						</div>
					</div>
					<div class="clearfix"> </div>
					
				</div>
			{% endblock properties %} 

templates/publicidad/index.html
{% extends "base/base.html" %}

templates/publicidad/publicos.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block banner %} 
{% endblock banner %}
{% block welcome %}
	<!-- welcome -->
				<div class="welcome"> 
					<h3 class="w3ls-title">Sectores publicos</h3> 
					<p class="w3title-text">Encuentra tu lugar en Caacupé </p>
					<div class="welcome-info">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">

							<div class="clearfix"> </div>
 

						</div>  
					</div>  	
				</div> 
	<!-- //welcome -->
    
{% endblock welcome %}
{% block properties %}
<div class="w3agile properties">
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/3.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Plaza Tte. Fariña </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="{% url 'publicidad:plazaTtefarina' %}"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div> 
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span>Parque Lagora</h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Plaza Tupasy Ykua </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Kurusu Peregrino </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Kurusu Campesino </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Municipalidad de Caacupe </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Horarios</b></p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Fundacion paraguaya </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>
					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/2.jpg' %}" alt="">
							<div class="view-caption rent-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Gobernacion de Cordillera </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b> </p>
							<p><b>Horarios</b> </p>
						</div>
					</div>

					<div class="properties-bottom">
						<div class="properties-img">
							<img src="{% static 'images/1.jpg' %}" 	alt="">
							<div class="view-caption">
								<h4><span class="glyphicon glyphicon-map-marker"></span> Teatro Municipal </h4>  
							</div>
						</div>
						<div class="w3ls-text">
							<h5><a href="single.html"> Ver </a></h5>
							<p><b>Descripción</b></p>
							<p><b>Ubicación</b></p>
							<p><b>Horarios</b></p>
						</div>
					</div>
					<div class="clearfix"> </div>
					
				</div>
    
{% endblock properties %}